version: "3.3"

services:
  nginx:
    build:
      context: .
      dockerfile: docker/Nginx.Dockerfile
    ports:
      - 8051:80
    links:
      - fpm
    volumes:
      - ./:/var/www/profilancegroup
  fpm:
    build:
      context: .
      dockerfile: docker/Fpm.Dockerfile
    volumes:
      - ./:/var/www/profilancegroup
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    links:
      - postresql
  postgresql:
    build:
      context: .
      dockerfile: docker/Postgres.Dockerfile
    ports:
      - 54322:5432
    environment:
      POSTGRES_DB: "profilancegroup"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
