version: "3.3"

services:
  nginx:
    build:
      context: .
      dockerfile: docker/Nginx.Dockerfile
    ports:
      - "8051:80"
    links:
      - fpm
    volumes:
      - ./:/var/www/laravel-link-shorter
  fpm:
    build:
      context: .
      dockerfile: docker/Fpm.Dockerfile
    volumes:
      - ./:/var/www/laravel-link-shorter
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    links:
      - postgresql
  postgresql:
    build:
      context: .
      dockerfile: docker/Postgres.Dockerfile
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
